### ISSUE TITLE
github.com\clausecker\nfc\v2@v2.1.4\nfc.go:208:17: undefined: context

### ISSUE THREAD

**Issue by Sprite137** [clausecker/nfc#14]
Hello，I get a err when I use code 'fmt.PrintIn(nfc.Version())'
![image](https://github.com/user-attachments/assets/fdc0f348-a59f-4fd1-9d1a-8b72c28aff39)
I am using go-1.22.5 and have installed libnfc-1.8.0

**Comment by Sprite137** [comment]
by the way,  I run it on Windows10

**Comment by clausecker** [comment]
Greetings, do not post pictures of error messages please.  Instead, post the error message as text.

**Comment by clausecker** [comment]
Likely a duplicate of #11.  Are you compiling with cgo disabled by chance?

**Comment by Sprite137** [comment]
> Greetings, do not post pictures of error messages please. Instead, post the error message as text.

Thanks, I will notice it.

**Comment by Sprite137** [comment]
> Likely a duplicate of #11. Are you compiling with cgo disabled by chance?

OK, there we go!

**Comment by clausecker** [comment]
Duplicate of #11.  Please enable cgo to use this library.  You'll also need to install the libnfc.
